apiVersion: apps/v1
kind: Deployment
metadata:
  name: mexant-deployment
  labels:
    app: mexant
spec:
  replicas: 15
  selector:
    matchLabels:
      app: mexant
  template:
    metadata:
      labels:
        app: mexant
    spec:
      containers:
      - name: mexant 
        image: 203981192956.dkr.ecr.us-east-1.amazonaws.com/mexant:8
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
  selector:
    app: mexant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80